### ISSUE TITLE
Update memory test to use real random generation

### ISSUE THREAD

**Issue by brunofalmeida** [HeronMkII/obc#84]
Now that the test harness properly supports random number seeding so we can do actually do random tests, update the test in `harness_tests/mem` so it makes use of this.

- Don't call `srand()` or `srandom()` in the test file because this is taken care of in the test harness initialization
- Please use separate functions for randomized tests (don't put hardcoded values and random values in the same function)

**Comment by Tahreeem** [comment]
commit b1f88dd1137e9a9769ed35225452b02fc7a15287 addresses this
