### ISSUE TITLE
Recover auto data collection info on restart

### ISSUE THREAD

**Issue by brunofalmeida** [HeronMkII/obc#88]
Currently, we lose the state of automatic data collection every time OBC restarts. Need to store in EEPROM whether ADC is enabled and what the period is for each type of data block whenever any of those values changes (in `commands.c`), and recover that information on restart with a new `init_auto_data_col()` function.

**Comment by Tahreeem** [comment]
commit 0ac0e68c3605d183096d8c4a56609b1531c01e2b now addresses this
