### ISSUE TITLE
Update comms delay and antenna deployment for OBC v3 PCB

### ISSUE THREAD

**Issue by brunofalmeida** [HeronMkII/obc#94]
- Blink warning LED with increasing frequency during the 30 min delay and faster for a few seconds before the deployment sequence starts
- After attempting to deploy via I2C, check if an I2C read fails or the deployment didn't happen - actuate the GPIO release A/B (each for 5 seconds) if necessary

**Comment by BrytniR** [comment]
LED blink before antenna deploys, blink faster when about to deploy
ANT_DEP_WARN = LED to blink in obc
ANT_REL_B/ANT_REL_A = Pins to deploy antenna when set high(?)

**Comment by brunofalmeida** [comment]
Make sure that the deployment code sets the I2C bridge registers to have the maximum frequency and time-out (and make sure the time-out bit is enabled).
